### ISSUE TITLE
Container. __aexit__ ignores exc_... values

### ISSUE THREAD

**Issue by lewicki** [hynek/svcs#112]
Hi,
I'm having great fun working with this clean package, but I encountered an issue.
If there is any error in Container.__ aexit __ it is ignored and passed down the chain. Is it a bug or a feature?

```
@asynccontextmanager
async def session_factory(container: svcs.Container) -> AsyncIterator[AsyncSession]:
    session_maker: async_sessionmaker[AsyncSession] = container.get(AsyncSessionMaker)
    async with session_maker() as session:
        async with session.begin():
            print("Session created")
            yield session
            print("Session committed")


registry.register_factory(AsyncSession, session_factory)


async with Container(registry) as container:
    ... # some code triggering the session creation
    raise Exception("Any exception")
```
The session is first committed and then the error is raised.
What do you think of 

```
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        if exc_type is not None:
            raise exc_val.with_traceback(exc_tb)
        await self.aclose()
```
?

**Comment by lewicki** [comment]
Small correction for proposed solution :)

```
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        await self.aclose(exc_type, exc_val, exc_tb)

    async def aclose(self,
                     exc_type: type[BaseException] | None = None,
                     exc_val: BaseException | None = None,
                     exc_tb: TracebackType | None = None,
                     ) -> None:
        """
        Run *all* registered cleanups -- synchronous **and** asynchronous.

        Errors are logged at warning level, but otherwise ignored.

        Also works with synchronous services, so in an async application, just
        use this.

        Hint:
            The container can be used again after this. Closing it is an
            idempotent way to reset it.
        """
        for name, cm in reversed(self._on_close):
            try:
                if isinstance(cm, AbstractContextManager):
                    cm.__exit__(exc_type, exc_val, exc_tb)
                else:
                    await cm.__aexit__(exc_type, exc_val, exc_tb)

            except Exception:  # noqa: BLE001, PERF203
                log.warning(
                    "Container clean up failed for %r.",
                    name,
                    exc_info=True,
                    extra={"svcs_service_name": name},
                )

        if self._lazy_local_registry is not None:
            await self._lazy_local_registry.aclose()
        self._on_close.clear()
        self._instantiated.clear()

```
and the same for sync version.

**Comment by hynek** [comment]
Generally speaking, it's a feature that errors in cleanup are logged, but don't explode. It's usually what you want (see also chapter 2 of [_Release It!_](https://pragprog.com/titles/mnee2/release-it-second-edition/): "Case Study: The Exception That Grounded An Airline").

What exactly are you trying to achieve, practically? It's a bit tricky to deduct your intent from code.

---

Either way, you're always free to wrap your cleanups and do whatever pleases you, though!

**Comment by lewicki** [comment]
Maybe I'm missing something, but I don't see a big change with my fix. I'm not changing the logic of cleaning up of factory errors.

```
import svcs

reg = svcs.Registry()

def unclean_factory() -> int:
    yield 123
    raise Exception("Exception that should only be logged")

reg.register_factory(int, unclean_factory)
with svcs.Container(reg) as con:
    _ = con.get(int)
print("Still running")
```
My patch has no impact on such code. In both cases error is only logged:
```
Container clean up failed for 'builtins.int'.
Traceback (most recent call last):
  File "/data/work/testing/testsvcs/.venv/lib/python3.12/site-packages/svcs/_core.py", line 565, in close
    cm.__exit__(exc_type, exc_val, exc_tb)  # or cm.__exit__(None, None, None)
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/data/work/testing/34uvclusters/testsvcs/test.py", line 16, in unclean_factory
    raise Exception("Exception that should only be logged")
Exception: Exception that should only be logged
Still running
```
Let me explain my use case. I wanted to use context of the container as my "unit of work". If I use session - session maker creates a new instance. If anything goes wrong in the scope of the container context - my yielded session is rolled back.
Without my fix the error is not propagated to the factory. Look at my initial example. Session is not committed and not rolled back.

**Comment by lewicki** [comment]
I just realized that my example is not the best as begin() does implicit magic. Maybe that one is better. Without my fix if there is any error in scope of the container context, session stays in zombie state (locking DB).

```
@asynccontextmanager
async def session_factory(container: svcs.Container):
    session_maker = container.get(AsyncSessionMaker)
    async with session_maker() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()
```

**Comment by hynek** [comment]
OK two topics are in my head and I'll let out the one this topic is not about first:

I too am a huge fan of the UoW pattern, so big I wrote an internal package for transaction management, because I didn't want to accidentally start transactions. Essentially, you only get the UoW object after begin().

That said in your logic, move the await rollback() into the finally clause. A rollback in a non-active transaction is a NOP. I personally go as far as requiring explicit commits.

---

To your actual topic:

I could live with allowing people to receive errors in their factories, but maybe I'm being super dense, but I don't see how that is not breaking to be on by default?

If my factory looks like this:

```python
def factory():
    inst = create()

    yield inst

    inst.close()
```

throwing an exception into the factory would cause it to never close – or should I finish my coffee before posting??

**Comment by lewicki** [comment]
No, you're right even before coffee ;) I have to think if there is a clean merge for both cases.

**Comment by lewicki** [comment]
> That said in your logic, move the await rollback() into the finally clause. A rollback in a non-active transaction is a NOP. I personally go as far as requiring explicit commits.

Got it :) I'll close my PR and the issue. Here is the fixed code (IIRC you don't need to close session if using async with).

```
@asynccontextmanager
async def session_factory(container: svcs.Container):
    session_maker = container.get(AsyncSessionMaker)
    async with session_maker() as session:
        try:
            yield session
            await session.commit()
        finally:
            await session.rollback()
```
