### ISSUE TITLE
FastAPI: The server does not support "state" in the lifespan scope

### ISSUE THREAD

**Issue by bootc** [hynek/svcs#80]
When using the FastAPI integration the server fails to start up:

```
RuntimeError: The server does not support "state" in the lifespan scope.
```

This can be reproduced with this minimal reproducer:

```python
import svcs
from fastapi import FastAPI


@svcs.fastapi.lifespan
async def lifespan(app: FastAPI, registry: svcs.Registry):
    yield


app = FastAPI(
    lifespan=lifespan,
)
```

This is using:
* Python 3.12.2
* FastAPI 0.110.1
* svcs 24.1.0
* Hypercorn 0.16.0

Interestingly I can't reproduce this with Gunicorn or Uvicorn, so I will dig into this some more.

**Comment by bootc** [comment]
While I can't see this documented anywhere, I think this is a limitation of Hypercorn. It looks like it doesn't allow contributing state in the lifecycle hook, so if the lifecycle hook yields anything but `None` you get this message from Starlette that underpins FastAPI.

**Comment by hynek** [comment]
@pgjones is this accurate and on purpose?

Does this mean _svcs_ can't be used with hypercorn? 😬

**Comment by bootc** [comment]
That's certainly what I found.

I ended up going down a different route entirely for my app, as I needed code that worked both through FastAPI _and_ the CLI, and wanted something implementation agnostic. In the end I sub-classed `Container` so it set a `ContextVar` in the `__enter__` and `__aenter__` methods, now my code can effectively just get the Container out of the ContextVar no matter how or where the Container is set up.

After that, it was pretty trivial to write a custom ASGI middleware to handle setting up both the Registry and Containers for my use; what I have below isn't ready for upstreaming but works fantastically for me:

```python
class SvcsMiddleware:
    """
    svcs glue middleware.

    This is simpler than either the FastAPI or Starlette middlewares included with svcs
    as all it has to do is create a Registry (and register our services) in the
    lifespan hook, then use our customised Container around the requiest.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app
        self.registry = Registry()

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        # For requests, wrap our Container around it.
        if scope["type"] in {"http", "websocket"}:
            with Container(self.registry):
                await self.app(scope, receive, send)
            return None

        # For lifespan hooks, wrap our Registry with our services around it.
        if scope["type"] == "lifespan":
            # Add our services to the registry
            register_deps(self.registry)
            async with self.registry:
                await self.app(scope, receive, send)
            return None

        return await self.app(scope, receive, send)
```

**Comment by pgjones** [comment]
Hypercorn does not, as yet, support the ASGI state extension. So if that is required then I guess not.

**Comment by hynek** [comment]
Oh, I had no idea that's an ASGI extension… When I implemented it, I thought it's some kind of Starlette thing!

**Comment by hynek** [comment]
this should work as of hypercorn 0.17 – thanks @pgjones! 🎉
