### ISSUE TITLE
Sync context managers are not entered in aget

### ISSUE THREAD

**Issue by adrianschneider94** [hynek/svcs#87]
To reproduce:
```python
import asyncio

import svcs
from svcs import Registry

registry = Registry()


def sync_generator() -> int:
    yield 3


registry.register_factory(int, sync_generator)


async def main():
    async with svcs.Container(registry=registry) as container:
        print(await container.aget(int))
        # Prints <contextlib._GeneratorContextManager object at 0x0000024E4FACACF0>
        # instead of 3
        


if __name__ == '__main__':
    asyncio.run(main())

```

Adding 

```python
class Container:
    ...

    async def aget(self, *svc_types: type) -> object:
        """
        Same as :meth:`get` but instantiates asynchronously, if necessary.

        Also works with synchronous services, so in an async application, just
        use this.
        """
        rv = []
        for svc_type in svc_types:
            cached, svc, name, enter = self._lookup(svc_type)
            if cached:
                rv.append(svc)
                continue

            if enter and isinstance(svc, AbstractAsyncContextManager):
                self._on_close.append((name, svc))
                svc = await svc.__aenter__()
                
            elif isawaitable(svc):
                svc = await svc
            
           # New =>
            elif enter and isinstance(svc, AbstractContextManager):
                self._on_close.append((name, svc))
                svc = svc.__enter__()
           # <= New

            self._instantiated[svc_type] = svc

            rv.append(svc)

        if len(rv) == 1:
            return rv[0]

        return rv
```

works.

**Comment by tuukkamustonen** [comment]
@adrianschneider94 @hynek Potentially a stupid question, but isn't this a bit of a scary feature - a sync context manager might do sync IO, potentially bringing whole event loop to a halt.

Wouldn't safer default be to _raise_ in case a sync context manager (and not async) is detected? Or run it in a thread?

(Shouldn't call sync dependencies from async context in the first place, but this could be a good mechanism to explicitly block that?)

**Comment by hynek** [comment]
Not all context managers do I/O, so I don't think it's warranted to stand in our users's way?

**Comment by tuukkamustonen** [comment]
Not necessarily, but it _is_ risky. Lots of shooting in the leg will happen.

Maybe a require an extra flag to enable that. Yeah, annoying but the alternative is bad, too... 🤔

**Comment by adrianschneider94** [comment]
Definitely a good point...
In my case it's indeed a dependency without I/O, so no problem here.

I also think, the best solution would be to raise by default and allow this by passing something like `pure=True`, `without_sideeffects=True` or `allow_from_async=True`.
