### ISSUE TITLE
Async factories don't trigger context manager

### ISSUE THREAD

**Issue by tuukkamustonen** [hynek/svcs#96]
```py
async def factory(c: Container):
    some_stuff = await c.aget(SomeOtherType)  # async factory because we want to do this
    return SomeType(some_stuff)

registry.register_factory(SomeType, factory)
```

Let's say `SomeType` is also context manager. The code won't enter/exit the context manager because [that only happens if the factory is not awaitable](https://github.com/hynek/svcs/blob/8ed3db3c8f742730a4d9e51a0d676b3c31423681/src/svcs/_core.py#L1008-L1015).

**Comment by hynek** [comment]
I think that’s fixed in https://github.com/hynek/svcs/pull/93?

**Comment by tuukkamustonen** [comment]
I think that's different. #93 was about entering non-async context managers, when `aget()` and sync factory is used.

This is about using async factories?
